# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0004_auto_20160414_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 1, 44, 34, 296683, tzinfo=utc)),
        ),
    ]
