# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 01:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0005_auto_20160414_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_time',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 4, 15, 1, 48, 42, 537882, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(auto_now=True, default=datetime.datetime(2016, 4, 15, 1, 48, 50, 297326, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
