# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0006_auto_20160414_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 15, 2, 7, 7, 631090, tzinfo=utc)),
        ),
    ]
