# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0008_auto_20160414_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 15, 23, 22, 48, 770992, tzinfo=utc)),
        ),
    ]
