# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0011_auto_20160417_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2016, 4, 17)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 17, 10, 15, 13, 171715, tzinfo=utc)),
        ),
    ]
