# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0013_auto_20160505_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='HNApp.Patient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 7)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 7, 8, 35, 22, 249182, tzinfo=utc)),
        ),
    ]
