# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0017_auto_20160507_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='person',
            name='known_allergies',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 8)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 8, 19, 49, 6, 45089, tzinfo=utc)),
        ),
    ]
