# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0018_auto_20160508_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.TextField(max_length=20)),
                ('time', models.DateTimeField(default=datetime.date(2016, 5, 8))),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HNApp.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 9, 0, 50, 20, 908912, tzinfo=utc)),
        ),
    ]
