# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0019_auto_20160508_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='time',
            field=models.DateTimeField(default=datetime.date(2016, 5, 9)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 9)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 9, 8, 3, 56, 138898, tzinfo=utc)),
        ),
    ]
