# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HNApp', '0020_auto_20160509_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 9, 9, 43, 28, 632505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(default=datetime.date(2016, 5, 9)),
        ),
    ]
